name: Publish a Python distribution to test PyPI
on:
  push:
    branches:
      - 'master'
    tags:
      - v**
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - uses: pypa/gh-action-pypi-publish@release/v1
       with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
          print_hash: true