- name: Publish a Python distribution to test PyPI
  on:
    push:
      branches:
        - 'master'
      tags:
        - v**
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    user: __token__
    password: ${{ secrets.PYPI_API_TOKEN }}
    verbose: true
    print_hash: true