name: Publish to test PyPI
on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  deploy:

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
          print_hash: true